spring:
  application:
    name: student-management

  datasource:
    url: jdbc:postgresql://localhost:5432/student_management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  
    show-sql: true     
    properties:
      hibernate:
        format_sql: true 
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
